package models;

public enum ReporteTipo {
    TENDENCIAS_GLUCEMIA,
    PATRONES_GLUCEMIA,
    RANGOS_GLUCEMIA,
    PROMEDIOS_GLUCEMIA,
    HB1AC_HISTORICO,
    DOSIFICACION_INSULINA,
    CANTIDAD_CARBOHIDRATOS,
    NOTAS_OBSERVACIONES;
}
